---
Feature:
  - head-branch:
      - ^feat

Fix:
  - head-branch:
      - ^fix

CI:
  - changed-files:
      - any-glob-to-any-file:
          - .github/dependabot.yml
          - .github/labeler.yml
          - .github/workflows/*
  - head-branch:
      - ^ci

Documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
  - head-branch:
      - ^docs

Alacritty:
  - changed-files:
      - any-glob-to-any-file:
          - alacritty/**/*

Ansible:
  - changed-files:
      - any-glob-to-any-file:
          - roles/**/*
          - bootstrap.yml

Neovim:
  - changed-files:
      - any-glob-to-any-file:
          - neovim/**/*

Vim:
  - changed-files:
      - any-glob-to-any-file:
          - vim/**/*

Starship:
  - changed-files:
      - any-glob-to-any-file:
          - starship/**/*

Taskfile:
  - changed-files:
      - any-glob-to-any-file:
          - Taskfile.yml
          - ThemeTasks.yml

Wezterm:
  - changed-files:
      - any-glob-to-any-file:
          - wezterm/**/*

Zsh:
  - changed-files:
      - any-glob-to-any-file:
          - zsh/**/*
