---
ci:
  - changed-files:
    - any-glob-to-any-file: 
      - .github/workflows/*
      - .github/labeler.yml

docs:
  - changed-files:
    - any-glob-to-any-file: 
      - "**/*.md"

Alacritty:
  - changed-files:
    - any-glob-to-any-file: 
      - alacritty/**/*

Helix:
  - changed-files:
    - any-glob-to-any-file: 
      - helix/**/*

Neovim:
  - changed-files:
    - any-glob-to-any-file: 
      - neovim/**/*

Vim:
  - changed-files:
    - any-glob-to-any-file: 
      - vim/**/*

Wezterm:
  - changed-files:
    - any-glob-to-any-file: 
      - wezterm/**/*

zsh:
  - changed-files:
    - any-glob-to-any-file: 
      - zsh/**/*
