---
version: '3'

vars:
  ALACRITTY_CONFIG_DIR: ~/.config/alacritty
  ALACRITTY_DARK_THEME: rose-pine
  ALACRITTY_LIGHT_THEME: rose-pine-dawn
  GTK_DARK_THEME: Mint-Y-Dark-Red
  GTK_LIGHT_THEME: Mint-Y-Red

tasks:
  change-theme-linux:
    desc: Switch from one theme to another.
    internal: true
    label: change theme in {{.WHERE}}
    platforms: [linux]
    silent: true
    requires:
      vars:
        - NEW
        - OLD
        - WHERE
    status:
      - '[ ! -f {{.WHERE}} ]'
    cmds:
      - sed --follow-symlinks -i 's/{{.OLD}}/{{.NEW}}/' {{.WHERE}}

  change-theme-darwin:
    desc: Switch from one theme to another.
    internal: true
    label: change theme in {{.WHERE}}
    platforms: [darwin]
    silent: true
    requires:
      vars:
        - NEW
        - OLD
        - WHERE
    vars:
      FILE_PATH:
        sh: "[ -h {{.WHERE}} ] && readlink -fn {{.WHERE}} || echo {{.WHERE}}"
    status:
      - '[ ! -f {{.WHERE}} ]'
    cmds:
      - sed -i '' -e 's/{{.OLD}}/{{.NEW}}/' "{{.FILE_PATH}}"

  change-cinnamon-theme:
    internal: true
    platforms: [linux]
    silent: true
    requires:
      vars:
        - COLOR_SCHEME
        - GTK_THEME
    cmds:
      - gsettings set org.cinnamon.desktop.interface gtk-theme {{.GTK_THEME}}
      - gsettings set org.cinnamon.theme name {{.GTK_THEME}}
      - gsettings set org.gnome.desktop.interface gtk-theme {{.GTK_THEME}}
      - gsettings set org.x.apps.portal color-scheme {{.COLOR_SCHEME}}

  light:alacritty:
    cmds:
      - task: change-theme-linux
        vars:
          NEW: "{{.ALACRITTY_LIGHT_THEME}}.yml"
          OLD: "{{.ALACRITTY_DARK_THEME}}.yml"
          WHERE: "{{.ALACRITTY_CONFIG_DIR}}/alacritty.yml"
      - task: change-theme-linux
        vars:
          NEW: "{{.ALACRITTY_LIGHT_THEME}}.toml"
          OLD: "{{.ALACRITTY_DARK_THEME}}.toml"
          WHERE: "{{.ALACRITTY_CONFIG_DIR}}/alacritty.toml"
      - task: change-theme-darwin
        vars:
          NEW: "{{.ALACRITTY_LIGHT_THEME}}.yml"
          OLD: "{{.ALACRITTY_DARK_THEME}}.yml"
          WHERE: "{{.ALACRITTY_CONFIG_DIR}}/alacritty.yml"
      - task: change-theme-darwin
        vars:
          NEW: "{{.ALACRITTY_LIGHT_THEME}}.toml"
          OLD: "{{.ALACRITTY_DARK_THEME}}.toml"
          WHERE: "{{.ALACRITTY_CONFIG_DIR}}/alacritty.toml"

  light:cinnamon:
    cmds:
      - task: change-cinnamon-theme
        vars:
          COLOR_SCHEME: prefer-light
          GTK_THEME: "{{.GTK_LIGHT_THEME}}"

  light:
    desc: Switch to light theme.
    deps:
      - task: light:cinnamon
      - task: light:alacritty

  dark:alacritty:
    cmds:
      - task: change-theme-linux
        vars:
          NEW: "{{.ALACRITTY_DARK_THEME}}.yml"
          OLD: "{{.ALACRITTY_LIGHT_THEME}}.yml"
          WHERE: "{{.ALACRITTY_CONFIG_DIR}}/alacritty.yml"
      - task: change-theme-linux
        vars:
          NEW: "{{.ALACRITTY_DARK_THEME}}.toml"
          OLD: "{{.ALACRITTY_LIGHT_THEME}}.toml"
          WHERE: "{{.ALACRITTY_CONFIG_DIR}}/alacritty.toml"
      - task: change-theme-darwin
        vars:
          NEW: "{{.ALACRITTY_DARK_THEME}}.yml"
          OLD: "{{.ALACRITTY_LIGHT_THEME}}.yml"
          WHERE: "{{.ALACRITTY_CONFIG_DIR}}/alacritty.yml"
      - task: change-theme-darwin
        vars:
          NEW: "{{.ALACRITTY_DARK_THEME}}.toml"
          OLD: "{{.ALACRITTY_LIGHT_THEME}}.toml"
          WHERE: "{{.ALACRITTY_CONFIG_DIR}}/alacritty.toml"

  dark:cinnamon:
    cmds:
      - task: change-cinnamon-theme
        vars:
          GTK_THEME: "{{.GTK_DARK_THEME}}"
          COLOR_SCHEME: prefer-dark

  dark:
    desc: Switch to dark theme.
    deps:
      - task: dark:cinnamon
      - task: dark:alacritty
