---
- name: Install packages
  connection: local
  hosts: localhost
  tasks:
    - name: Install homebrew packages
      when: ansible_facts['distribution'] == "MacOSX"
      community.general.homebrew:
        name:
          - fd
          - fzf
          - go-task
          - helix
          - lazygit
          - neovim
          - ripgrep
          - starship
          - stow
