---
- name: Install packages
  connection: local
  hosts: localhost
  tasks:
    - name: Install packages on macOS
      when: ansible_facts['distribution'] == "MacOSX"
      community.general.homebrew:
        package:
          - fd
          - fzf
          - go-task
          - helix
          - lazygit
          - neovim
          - ripgrep
          - starship
          - stow
    - name: Install packages on Linux Mint
      when: ansible_facts['distribution'] == "Linux Mint"
      apt:
        package:
          - fd-find
          - fzf
          - git
          - neovim
          - ripgrep
          - stow
          - task
          - vim
    - name: Install packages on Fedora
      when: ansible_facts['distribution'] == "Fedora"
      dnf:
        pkg:
          - fd-find
          - fzf
          - git
          - go-task
          - neovim
          - ripgrep
          - stow
          - vim
