---
- name: Install packages
  connection: local
  hosts: localhost
  tasks:
    - name: macOS packages installed
      when: ansible_facts['distribution'] == "MacOSX"
      community.general.homebrew:
        package:
          - fd
          - fzf
          - go-task
          - helix
          - lazygit
          - neovim
          - ripgrep
          - starship
    - name: Linux Mint packages installed
      when: ansible_facts['distribution'] == "Linux Mint"
      apt:
        package:
          - fd-find
          - fzf
          - git
          - jq
          - neovim
          - ripgrep
          - task
          - vim
          - yq
    - name: Fedora packages installed
      when: ansible_facts['distribution'] == "Fedora"
      dnf:
        pkg:
          - fd-find
          - fzf
          - git
          - go-task
          - neovim
          - ripgrep
          - vim

- name: Create symlinks
  connection: local
  hosts: localhost
  vars:
    xdg_config_dir: ~/.config
  tasks:
    - name: Symlink Vim config
      import_role:
        name: stow
      vars:
        target_path: "~"
        src_dir: "{{playbook_dir}}/vim"
    - name: Symlink Zsh config
      import_role:
        name: stow
      vars:
        target_path: "~"
        src_dir: "{{playbook_dir}}/zsh"
    - name: Symlink Task config
      import_role:
        name: stow
      vars:
        target_path: "~"
        src_dir: "{{playbook_dir}}/task"
    - name: Symlink Wezterm config
      import_role:
        name: stow
      vars:
        target_path: "~"
        src_dir: "{{playbook_dir}}/wezterm"
    - name: Symlink Neovim config
      import_role:
        name: stow
      vars:
        target_path: "{{ xdg_config_dir }}/nvim"
        src_dir: "{{playbook_dir}}/neovim"
    - name: Symlink Alacritty config
      import_role:
        name: stow
      vars:
        target_path: "{{ xdg_config_dir }}/alacritty"
        src_dir: "{{playbook_dir}}/alacritty"
    - name: Symlink Helix config
      import_role:
        name: stow
      vars:
        target_path: "{{ xdg_config_dir }}/helix"
        src_dir: "{{playbook_dir}}/helix"
