---
version: '3'

includes:
  theme: task/Taskfile.yml

vars:
  COMPLETIONS_PATH: ~/.oh-my-zsh/custom/completions

tasks:
  install:starship-linux:
    desc: Install starship.
    platforms: [linux]
    status:
      - starship --version
    cmds:
      - curl -sS https://starship.rs/install.sh | sh

  install:starship-darwin:
    desc: Install starship.
    platforms: [darwin]
    status:
      - starship --version
    cmds:
      - brew install starship

  install:omz:
    desc: Install Oh My Zsh.
    status:
      - '[ -d ~/.oh-my-zsh ]'
    cmds:
      # yamllint disable-line rule:line-length
      - sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

  completions:brew:
    desc: Install brew completions.
    platforms:
      - darwin
    cmds:
      - brew completions link

  completions:fd:
    desc: Install fd completions.
    cmds:
      # NOTE(kirillmorozov): fd might be installed under different names on
      # different OSes so try them all and ignore errors in the process.
      - cmd: fd --gen-completions=zsh > {{.COMPLETIONS_PATH}}/_fd
        ignore_error: true
      - cmd: fdfind --gen-completions=zsh > {{.COMPLETIONS_PATH}}/_fd
        ignore_error: true

  completions:ripgrep:
    desc: Install ripgrep completions.
    cmds:
      - rg --generate=complete-zsh > {{.COMPLETIONS_PATH}}/_rg

  completions:task:
    desc: Install task completions.
    cmds:
      - cmd: task --completion zsh 2> {{.COMPLETIONS_PATH}}/_task
        # NOTE(kirillmorozov): Task version that comes with Ubuntu 24.04 does
        # not have --completions flag.
        ignore_error: true

  completions:
    desc: Install completions for most used tools.
    deps:
      - install:omz
    cmds:
      - mkdir -p {{.COMPLETIONS_PATH}}
      - task: completions:brew
      - task: completions:fd
      - task: completions:ripgrep
      - task: completions:task

  bootstrap:
    desc: Bootstrap dotfiles.
    cmds:
      - task: install:omz
      - task: install:starship-linux
      - task: install:starship-darwin

  lint:yaml:
    desc: Lint YAML files using yamllint.
    aliases:
      - lint
    preconditions:
      - sh: yamllint --version
        msg: yamllint is not installed
    cmds:
      - yamllint .
