---
version: '3'

includes:
  theme: task/Taskfile.yml

vars:
  COMPLETIONS_PATH: ~/.oh-my-zsh/custom/completions

tasks:
  install:starship-linux:
    desc: Install starship.
    platforms: [linux]
    status:
      - starship --version
    cmds:
      - curl -sS https://starship.rs/install.sh | sh

  install:starship-darwin:
    desc: Install starship.
    platforms: [darwin]
    status:
      - starship --version
    cmds:
      - brew install starship

  install:omz:
    desc: Install Oh My Zsh.
    status:
      - '[ -d ~/.oh-my-zsh ]'
    cmds:
      # yamllint disable-line rule:line-length
      - sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

  completions:brew:
    desc: Install brew completions.
    platforms:
      - darwin
    cmds:
      - brew completions link

  bootstrap:
    desc: Bootstrap dotfiles.
    cmds:
      - task: install:omz
      - task: install:starship-linux
      - task: install:starship-darwin

  lint:yaml:
    desc: Lint YAML files using yamllint.
    aliases:
      - lint
    preconditions:
      - sh: yamllint --version
        msg: yamllint is not installed
    cmds:
      - yamllint .
