---
version: '3'

includes:
  theme: ThemeTasks.yml

vars:
  ALACRITTY_CONFIG_DIR: ~/.config/alacritty
  GLOBAL_TASK_FILE: ~/Taskfile.yml
  HELIX_CONFIG_DIR: ~/.config/helix
  NEOVIM_CONFIG_DIR: ~/.config/nvim
  VIMRC_PATH: ~/.vimrc
  WEZTERM_PATH: ~/.wezterm.lua
  ZSHRC_PATH: ~/.zshrc

tasks:
  install-starship:
    desc: Install starship
    platforms: [linux]
    status:
      - starship --version
    cmds:
      - curl -sS https://starship.rs/install.sh | sh

  # yamllint disable-line rule:key-duplicates
  install-starship:
    desc: Install starship
    platforms: [darwin]
    status:
      - starship --version
    cmds:
      - brew install starship

  install-omz:
    desc: Install Oh My Zsh
    status:
      - '[ -d ~/.oh-my-zsh ]'
    cmds:
      # yamllint disable-line rule:line-length
      - sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

  link-file:
    internal: true
    desc: Create a symbolic link to a file
    requires:
      vars:
        - SOURCE_FILE
        - TARGET_FILE
    status:
      - "[ -f {{.TARGET_FILE}} ]"
    cmds:
      - ln -sv {{.SOURCE_FILE}} {{.TARGET_FILE}}

  link-themes:
    cmds:
      - task: link-file
        vars:
          SOURCE_FILE: "{{.USER_WORKING_DIR}}/ThemeTasks.yml"
          TARGET_FILE: "{{.GLOBAL_TASK_FILE}}"

  bootstrap:
    desc: Bootstrap dotfiles
    deps:
      - install-omz
      - install-starship
      - link-themes
      - stow:alacritty
      - stow:helix
      - stow:neovim
      - stow:vim
      - stow:wezterm
      - stow:zsh

  clean-alacritty: rm -rf {{.ALACRITTY_CONFIG_DIR}}
  clean-helix: rm -rf {{.HELIX_CONFIG_DIR}}
  clean-neovim: rm -rf {{.NEOVIM_CONFIG_DIR}}
  clean-themes: rm -rf ~/Taskfile.yml
  clean-vim: rm -f {{.VIMRC_PATH}}
  clean-wezterm: rm -f {{.WEZTERM_PATH}}
  clean-zsh: rm -f {{.ZSHRC_PATH}}

  clean:
    desc: Clean up dotfiles
    summary: >
      Remove Helix, Alacritty and Neovim configuration directories as well as
      .vimrc, .zshrc and wezterm.lua files.
    cmds:
      - task: clean-alacritty
      - task: clean-helix
      - task: clean-neovim
      - task: clean-themes
      - task: clean-vim
      - task: clean-wezterm
      - task: clean-zsh

  lint-yaml:
    desc: Lint YAML files using yamllint
    aliases:
      - lint
    preconditions:
      - sh: yamllint --version
        msg: yamllint is not installed
    cmds:
      - yamllint .

  stow:package:
    internal: true
    preconditions:
      - sh: stow --version
        msg: GNU Stow is not installed
    requires:
      vars:
        - PACKAGE
        - TARGET
    cmds:
      - mkdir -pv {{.TARGET}}
      - stow {{.PACKAGE}} --verbose 3 --target {{.TARGET}}

  stow:alacritty:
    cmds:
      - task: stow:package
        vars:
          PACKAGE: alacritty
          TARGET: "{{.ALACRITTY_CONFIG_DIR}}"

  stow:helix:
    cmds:
      - task: stow:package
        vars:
          PACKAGE: helix
          TARGET: "{{.HELIX_CONFIG_DIR}}"

  stow:neovim:
    cmds:
      - task: stow:package
        vars:
          PACKAGE: neovim
          TARGET: "{{.NEOVIM_CONFIG_DIR}}"

  stow:vim:
    cmds:
      - task: stow:package
        vars:
          PACKAGE: vim
          TARGET: "~"

  stow:wezterm:
    cmds:
      - task: stow:package
        vars:
          PACKAGE: wezterm
          TARGET: "~"

  stow:zsh:
    cmds:
      - task: stow:package
        vars:
          PACKAGE: zsh
          TARGET: "~"
