---
version: '3'

includes:
  theme: task/Taskfile.yml

tasks:
  bootstrap:
    desc: Bootstrap dotfiles
    cmds:
      - ansible-playbook --ask-become-pass bootstrap.yml

  lint:yaml:
    desc: Lint YAML files using yamllint.
    aliases:
      - lint
    preconditions:
      - sh: yamllint --version
        msg: yamllint is not installed
    cmds:
      - yamllint .
