---
version: '3'

includes:
  theme: task/Taskfile.yml

vars:
  ALACRITTY_CONFIG_DIR: ~/.config/alacritty
  GLOBAL_TASK_FILE: ~/Taskfile.yml
  HELIX_CONFIG_DIR: ~/.config/helix
  NEOVIM_CONFIG_DIR: ~/.config/nvim
  VIMRC_PATH: ~/.vimrc
  WEZTERM_PATH: ~/.wezterm.lua
  ZSHRC_PATH: ~/.zshrc

tasks:
  install:starship:
    desc: Install starship.
    platforms: [linux]
    status:
      - starship --version
    cmds:
      - curl -sS https://starship.rs/install.sh | sh

  # yamllint disable-line rule:key-duplicates
  install:starship:
    desc: Install starship.
    platforms: [darwin]
    status:
      - starship --version
    cmds:
      - brew install starship

  install:omz:
    desc: Install Oh My Zsh.
    status:
      - '[ -d ~/.oh-my-zsh ]'
    cmds:
      # yamllint disable-line rule:line-length
      - sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

  stow:package:
    internal: true
    requires:
      vars:
        - PACKAGE
        - TARGET
    cmds:
      - mkdir -pv {{.TARGET}}
      - stow {{.PACKAGE}} --target {{.TARGET}}

  stow:alacritty:
    cmds:
      - task: stow:package
        vars:
          PACKAGE: alacritty
          TARGET: "{{.ALACRITTY_CONFIG_DIR}}"

  stow:helix:
    cmds:
      - task: stow:package
        vars:
          PACKAGE: helix
          TARGET: "{{.HELIX_CONFIG_DIR}}"

  stow:neovim:
    cmds:
      - task: stow:package
        vars:
          PACKAGE: neovim
          TARGET: "{{.NEOVIM_CONFIG_DIR}}"

  stow:task:
    cmds:
      - task: stow:package
        vars:
          PACKAGE: task
          TARGET: "~"

  stow:vim:
    cmds:
      - task: stow:package
        vars:
          PACKAGE: vim
          TARGET: "~"

  stow:wezterm:
    cmds:
      - task: stow:package
        vars:
          PACKAGE: wezterm
          TARGET: "~"

  stow:zsh:
    cmds:
      - task: stow:package
        vars:
          PACKAGE: zsh
          TARGET: "~"

  bootstrap:
    desc: Bootstrap dotfiles.
    deps:
      - install:omz
      - install:starship
      - stow:alacritty
      - stow:helix
      - stow:neovim
      - stow:task
      - stow:vim
      - stow:wezterm
      - stow:zsh

  clean:alacritty: rm -rf {{.ALACRITTY_CONFIG_DIR}}
  clean:helix: rm -rf {{.HELIX_CONFIG_DIR}}
  clean:neovim: rm -rf {{.NEOVIM_CONFIG_DIR}}
  clean:task: rm -rf {{.GLOBAL_TASK_FILE}}
  clean:vim: rm -f {{.VIMRC_PATH}}
  clean:wezterm: rm -f {{.WEZTERM_PATH}}
  clean:zsh: rm -f {{.ZSHRC_PATH}}

  clean:
    desc: Clean up dotfiles.
    summary: >
      Remove Helix, Alacritty and Neovim configuration directories as well as
      .vimrc, .zshrc and wezterm.lua files.
    cmds:
      - task: clean:alacritty
      - task: clean:helix
      - task: clean:neovim
      - task: clean:themes
      - task: clean:vim
      - task: clean:wezterm
      - task: clean:zsh

  lint:yaml:
    desc: Lint YAML files using yamllint.
    aliases:
      - lint
    preconditions:
      - sh: yamllint --version
        msg: yamllint is not installed
    cmds:
      - yamllint .
