---
version: '3'

includes:
  theme: task/Taskfile.yml

vars:
  ALACRITTY_CONFIG_DIR: ~/.config/alacritty
  GLOBAL_TASK_FILE: ~/Taskfile.yml
  HELIX_CONFIG_DIR: ~/.config/helix
  NEOVIM_CONFIG_DIR: ~/.config/nvim

tasks:
  install:starship-linux:
    desc: Install starship.
    platforms: [linux]
    status:
      - starship --version
    cmds:
      - curl -sS https://starship.rs/install.sh | sh

  install:starship-darwin:
    desc: Install starship.
    platforms: [darwin]
    status:
      - starship --version
    cmds:
      - brew install starship

  install:completions:
    desc: Generate completions for most used tools.
    vars:
      COMPLETION_PATH: ~/.oh-my-zsh/custom/completions
    cmds:
      - brew completions link
      - fd --gen-completions=zsh > {{.COMPLETION_PATH}}/_fd
      - rg --generate=complete-zsh > {{.COMPLETION_PATH}}/_rg
      - task --completion zsh 2> {{.COMPLETION_PATH}}/_task

  install:omz:
    desc: Install Oh My Zsh.
    status:
      - '[ -d ~/.oh-my-zsh ]'
    cmds:
      # yamllint disable-line rule:line-length
      - sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

  stow:package:
    internal: true
    label: stow:{{.PACKAGE}}
    requires:
      vars:
        - PACKAGE
        - TARGET
    cmds:
      - mkdir -pv {{.TARGET}}
      - stow {{.OPTION}} {{.PACKAGE}} --target {{.TARGET}} --verbose

  stow:alacritty:
    cmds:
      - task: stow:package
        vars:
          OPTION: "{{.OPTION}}"
          PACKAGE: alacritty
          TARGET: "{{.ALACRITTY_CONFIG_DIR}}"

  stow:helix:
    cmds:
      - task: stow:package
        vars:
          OPTION: "{{.OPTION}}"
          PACKAGE: helix
          TARGET: "{{.HELIX_CONFIG_DIR}}"

  stow:neovim:
    cmds:
      - task: stow:package
        vars:
          OPTION: "{{.OPTION}}"
          PACKAGE: neovim
          TARGET: "{{.NEOVIM_CONFIG_DIR}}"

  stow:task:
    cmds:
      - task: stow:package
        vars:
          OPTION: "{{.OPTION}}"
          PACKAGE: task
          TARGET: "~"

  stow:vim:
    cmds:
      - task: stow:package
        vars:
          OPTION: "{{.OPTION}}"
          PACKAGE: vim
          TARGET: "~"

  stow:wezterm:
    cmds:
      - task: stow:package
        vars:
          OPTION: "{{.OPTION}}"
          PACKAGE: wezterm
          TARGET: "~"

  stow:zsh:
    cmds:
      - task: stow:package
        vars:
          OPTION: "{{.OPTION}}"
          PACKAGE: zsh
          TARGET: "~"

  stow:
    desc: Create symlinks to all configuration files using GNU Stow.
    deps:
      - stow:alacritty
      - stow:helix
      - stow:neovim
      - stow:task
      - stow:vim
      - stow:wezterm
      - stow:zsh

  bootstrap:
    desc: Bootstrap dotfiles.
    cmds:
      - install:omz
      - stow
      - install:starship-linux
      - install:starship-darwin

  clean:
    desc: Clean up dotfiles.
    summary: Remove symlinks to all config files.
    deps:
      - for: [alacritty, helix, neovim, task, vim, wezterm, zsh]
        task: stow:{{.ITEM}}
        vars:
          OPTION: --delete

  lint:yaml:
    desc: Lint YAML files using yamllint.
    aliases:
      - lint
    preconditions:
      - sh: yamllint --version
        msg: yamllint is not installed
    cmds:
      - yamllint .
