---
version: '3'

includes:
  theme: task/Taskfile.yml

tasks:
  lint:yaml:
    desc: Lint YAML files using yamllint.
    aliases:
      - lint
    preconditions:
      - sh: yamllint --version
        msg: yamllint is not installed
    cmds:
      - yamllint .
