format = """
$username\
$hostname\
$localip\
$shlvl\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$package\
$deno\
$elm\
$gleam\
$golang\
$helm\
$lua\
$nodejs\
$python\
$terraform\
$vagrant\
$memory_usage\
$aws\
$azure\
$nats\
$direnv\
$env_var\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$container\
$netns\
$shell\
$character"""

[azure]
disabled = false

[kubernetes]
disabled = false
