format = """
$username\
$directory\
$jj_bookmark\
$jj_change\
$jj_metrics\
$jj_status\
$package\
$rust\
$golang\
$helm\
$nodejs\
$python\
$terraform\
$azure\
$kubernetes\
$nats\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$container\
$netns\
$shell\
$character"""

[azure]
disabled = false

[kubernetes]
disabled = false
format = 'on [$symbol $context(\($namespace\))]($style) '

[shell]
disabled = false
fish_indicator = '󰈺'

[status]
disabled = false
