[[language]]
name = "bash"
auto-format = true
formatter = { command = "shfmt", args = ["-i", "2", "-bn", "-ci", "-sr"] }

[[language]]
name = "dockerfile"
auto-format = true
formatter.command = "dockerfmt"

[[language]]
name = "git-commit"
rulers = [55, 72]

[[language]]
name = "python"
auto-format = true
formatter = { command = "ruff", args = ["format", "-"] }

[[language]]
name = "go"
auto-format = true
formatter.command = "gofumpt"

[[language]]
name = "json"
formatter = { command = "jq", args = ["."] }

[[language]]
name = "yaml"
auto-format = true
formatter.command = "yamlfmt"
formatter.args = [
	"-formatter",
	"include_document_start=true",
	"-formatter",
	"retain_line_breaks_single=true",
	"-formatter",
	"max_line_length=80",
	"-formatter",
	"scan_folded_as_literal=true",
	"-formatter",
	"pad_line_comments=2",
	"-formatter",
	"trim_trailing_whitespace=true",
  "-in",
]
