[[language]]
auto-format = true
formatter = { args = ["-i", "2", "-bn", "-ci", "-sr"], command = "shfmt" }
name = "bash"

[[language]]
auto-format = true
formatter.command = "dockerfmt"
name = "dockerfile"

[[language]]
name = "git-commit"
rulers = [55, 72]

[[language]]
auto-format = true
formatter = { args = ["format", "-"], command = "ruff" }
name = "python"

[[language]]
auto-format = true
formatter.command = "gofumpt"
name = "go"

[[language]]
formatter = { args = ["-S", "."], command = "jq" }
name = "json"

[[language]]
auto-format = true
formatter = { args = ["--stdin"], command = "elm-format" }
name = "elm"

[[language]]
auto-format = true
formatter = { args = ["format", "--stdin"], command = "gleam" }
name = "gleam"

[[language]]
auto-format = true
formatter = { args = ["fmt", "-"], command = "deno" }
name = "javascript"

[[language]]
auto-format = true
formatter = { args = [
  "--column-width",
  "88",
  "--quote-style",
  "AutoPreferDouble",
  "-",
], command = "stylua" }
name = "lua"

[[language]]
auto-format = true
formatter.command = "rustfmt"
name = "rust"

[[language]]
auto-format = true
formatter = { args = ["fmt", "-"], command = "terraform" }
name = "hcl"

[[language]]
auto-format = true
formatter = { args = ["fmt", "-"], command = "terraform" }
name = "tfvars"

[[language]]
auto-format = true
formatter.args = [
  "-formatter",
  "include_document_start=true",
  "-formatter",
  "retain_line_breaks_single=true",
  "-formatter",
  "max_line_length=80",
  "-formatter",
  "scan_folded_as_literal=true",
  "-formatter",
  "pad_line_comments=2",
  "-formatter",
  "trim_trailing_whitespace=true",
  "-in",
]
formatter.command = "yamlfmt"
name = "yaml"

[[language]]
formatter = { args = ["fmt", "-"], command = "taplo" }
name = "toml"
