---
dest_per_system:
  Darwin: ~/Library/Fonts/
  Linux: ~/.local/share/fonts
fonts:
  - archive: CascadiaCode.zip
    name_prefix: CaskaydiaCoveNerdFont
  - archive: FiraCode.zip
    name_prefix: FiraCodeNerdFont
