---
- name: Install macOS packages
  ansible.builtin.include_tasks:
    file: install-macos-packages.yml
    apply:
      tags:
        - packages
        - macos
  when: ansible_facts["distribution"] == "MacOSX"
  tags:
    - packages
    - macos
- name: Install deb packages
  ansible.builtin.include_tasks:
    file: install-deb-packages.yml
    apply:
      tags:
        - packages
        - linux
        - deb
        - linux_mint
  when: ansible_facts["distribution"] == "Linux Mint"
  tags:
    - packages
    - linux
    - deb
    - linux_mint
- name: Install rpm packages
  ansible.builtin.include_tasks:
    file: install-rpm-packages.yml
    apply:
      tags:
        - packages
        - linux
        - rpm
        - fedora
  when: ansible_facts["distribution"] == "Fedora"
  tags:
    - packages
    - linux
    - rpm
    - fedora
- name: Install Rust programs using Cargo
  community.general.cargo:
    locked: true
    path: ~/.local
    name:
      # NOTE(kirill.morozov): Temporary measure until JJ support in Starship is
      # released.
      - starship
  tags:
    - packages
    - starship
- name: Install WezTerm terminfo
  ansible.builtin.include_tasks:
    file: install-wezterm-terminfo.yml
    apply:
      tags:
        - packages
        - terminfo
        - wezterm
  tags:
    - packages
    - terminfo
    - wezterm
