---
- name: Link brew completions
  ansible.builtin.command: brew completions link
  when: ansible_facts["distribution"] == "MacOSX"
  changed_when: false
- name: Include variables
  ansible.builtin.include_vars:
    file: config-links.yml
- name: Ensure completions directory exist
  ansible.builtin.file:
    path: "{{ development_machine_completions_path }}"
    state: directory
    mode: "0755"
- name: Install fd completions
  ansible.builtin.shell:
    cmd: >-
      fd --gen-completions=fish
      > {{ development_machine_completions_path }}/fd.fish
    creates: "{{ development_machine_completions_path }}/fd.fish"
- name: Install ripgrep completions
  ansible.builtin.shell:
    cmd: >-
      rg --generate=complete-fish
      > {{ development_machine_completions_path }}/rg.fish
    creates: "{{ development_machine_completions_path }}/rg.fish"
# FIXME(kirill.morozov): This doesn't work on macOS
# - name: Install task completions
#   ansible.builtin.shell:
#     cmd: >-
#       go-task --completion fish
#       > {{ development_machine_completions_path }}/task.fish
#     creates: "{{ development_machine_completions_path }}/task.fish"
