vim9script

# It is a text editor, not an IDE
# It probably has that feature built in
# Move with deliberate purpose
# The documentation is better than you imagine
# HJKL is not an important part of vim navigation
# Project drawers conflict with split windows, favor splits
# Visual clutter saps mental energy
# Use plugins sparingly
# Navigate by tags and search, not files
# If it feels hard, there is probably a better way
# You should understand every line in your vimrc
# UI "tabs" are probably not what you expect
# Don't seek mastery, seek proficiency

# Use spacebar as a leader key
g:mapleader = " "

# Make Vim snappier
set updatetime=100

# Suppress the banner
g:netrw_banner = 0
# Open in prior window
g:netrw_browse_split = 4
# Change from left splitting to right splitting
g:netrw_altv = 1
# Tree style view in netrw
g:netrw_liststyle = 3

# Do not use a swapfile for the buffer
set noswapfile

# Automatically read file again if it was changed outside vim
set autoread
# 'autoread' only kicks in on commands like :!, so check for outside changes
# on focus and buffer switch as well
augroup autoread_checktime
	autocmd!
	autocmd FocusGained,BufEnter * ++nested if getcmdwintype() == '' | checktime | endif
augroup END

# Automatically save before :next, :make etc
set autowrite

# Set title of the window
set title

# Switch on syntax highlighting
syntax enable

filetype plugin indent on

if has('termguicolors')
	set termguicolors
	for cs in ['catppuccin', 'wildcharm', 'zaibatsu', 'habamax', 'default']
		try
			execute 'colorscheme ' .. cs
			break
		catch /E185:/
			# colorscheme not found, try next
		endtry
	endfor
else
	colorscheme default
endif

# Show tabs, multiple consecutive spaces, trailing spaces and breaks
set list
if exists('+listchars')
	# Fall back to a simpler variant for older Vim versions
	set listchars=tab:»\ ,extends:›,precedes:‹,nbsp:␣,trail:·
	if has('patch-9.0.0000')
		set listchars+=lead:\ ,multispace:·
	endif
endif
&showbreak = '↪ '

# Turn on line numbers
set number
# Turn on relative line numbers
set relativenumber
# Show the line and column number of the cursor position
set ruler

# Screen columns that are highlighted
set colorcolumn=80

# Enable case insensitive searching
set ignorecase
# All searches are case insensitive unless there's a capital letter
set smartcase
# Highlight search results
set hlsearch
# Enable incremental searching
set incsearch

# Enable text wrapping
set wrap
# Tabs=4spaces
set tabstop=4
set shiftwidth=4
# Do not expand tab
set noexpandtab

# Number of items in popup menu
set pumheight=10

# Always show statusline
set laststatus=2

# Do smart autoindenting when starting a new line
set smartindent

# Splitting a window will put the new window below the current one
set splitbelow
# Splitting a window will put the new window right of the current one
set splitright

# If in Insert, Replace or Visual mode put a message on the last line
set showmode

# Delete comment character when joining commented lines.
set formatoptions+=j

# Minimal number of screen lines to keep above and below the cursor
set scrolloff=8
# Minimal number of screen columns to keep to the left and to the right of the
# cursor
set sidescrolloff=8

# Command-line completion operates in an enhanced mode
if has('wildmenu')
	set wildmenu
endif
# "noselect" appeared in the same era as wildtrigger() (9.1.1576)
if exists('+wildmode') && has('patch-9.1.1576')
	set wildmode=noselect:lastused,full
endif
if exists('+wildoptions') && has('patch-9.0.0000')
	set wildoptions=pum
endif
# Hide noise in completion
if has('wildignore')
	set wildignore+=*.pyc,*/.git/*,*/node_modules/*
endif

# Key mappings
# Search
nnoremap <Leader>/ :grep<Space>
nnoremap N Nzz
nnoremap n nzz
xnoremap * y/\V<C-r>=substitute(escape(@",'/\'),'\n','\\n','g')<CR><CR>
xnoremap <silent> <Leader>/ y:<C-U>execute 'grep -F ' .. shellescape(@", true)<CR>
# General navigation
nnoremap <Leader>b :buffer<Space>
nnoremap <C-S> :update<CR>
nnoremap <leader>f :find<Space>
nnoremap <silent> <Leader>' <ScriptCmd>ResumeLastCmd()<CR>
nnoremap <leader>h :vert<Space>help<Space>
# Window navigation
nnoremap <C-D> <C-D>zz
nnoremap <C-H> <C-W>h
nnoremap <C-J> <C-W>j
nnoremap <C-K> <C-W>k
nnoremap <C-L> <C-W>l
nnoremap <C-U> <C-U>zz
nnoremap <Leader>w <C-W>
# Open in a split
nnoremap gsf <C-w>vgf
# Moving selected lines
nnoremap <A-Down> :m<Space>.+1<CR>==
nnoremap <A-Up> :m<Space>.-2<CR>==
xnoremap <A-Down> :m<Space>'>+1<CR>gv=gv
xnoremap <A-Up> :m<Space>'<-2<CR>gv=gv
# Load git hunks into quickfix list
nnoremap <Leader>gq <ScriptCmd>GitHunksToQF()<CR>
# Quickfix list navigation
nnoremap <leader>cc :cclose<CR>
nnoremap <leader>co :copen<CR>
nnoremap [<C-Q> :cpfile<CR>zz
nnoremap [Q :crewind<CR>zz
nnoremap [q :cprevious<CR>zz
nnoremap ]<C-Q> :cnfile<CR>zz
nnoremap ]Q :clast<CR>zz
nnoremap ]q :cnext<CR>zz
# Location list navigation
nnoremap <leader>lc :lclose<CR>
nnoremap <leader>lo :lopen<CR>
nnoremap [<C-L> :lpfile<CR>zz
nnoremap [L :lrewind<CR>zz
nnoremap [l :lprevious<CR>zz
nnoremap ]<C-L> :lnfile<CR>zz
nnoremap ]L :llast<CR>zz
nnoremap ]l :lnext<CR>zz
# Argument list navigation
nnoremap [A :rewind<CR>
nnoremap [a :previous<CR>
nnoremap ]A :last<CR>
nnoremap ]a :next<CR>
# Tags navigation
nnoremap [t :tprevious<CR>zz
nnoremap ]t :tnext<CR>zz
nnoremap [T :trewind<CR>zz
nnoremap ]T :tlast<CR>zz
nnoremap [<C-T> :ptprevious<CR>zz
nnoremap ]<C-T> :ptnext<CR>zz
# Buffers navigation
nnoremap [B :brewind<CR>
nnoremap [b :bprevious<CR>
nnoremap ]B :blast<CR>
nnoremap ]b :bnext<CR>
# Clipboard
noremap <leader>y "+y
noremap <leader>p "+p
noremap <leader><s-p> "+<s-p>
# Make
nnoremap <Leader>m :make<Space>
# Open file in a vertical split
cnoremap <expr> <C-v> <SID>VertSplitFind()

# Use ripgrep for search if it's installed
if executable('rg')
	&grepprg = "rg --vimgrep --smart-case --follow --hidden --glob '!.git/**'"
	# --vimgrep emits file:line:col:text, keep the column for exact jumps
	&grepformat = '%f:%l:%c:%m'
endif

def VertSplitFind(): string
	if getcmdtype() != ':'
		return "\<C-v>"
	endif
	var line = getcmdline()
	if line =~# '^\s*find\>'
		var new = substitute(line, '^\s*find\>', 'vert sfind', '')
		return "\<C-U>" .. new .. "\<CR>"
	endif
	if line =~# '^\s*buffer\>'
		var new = substitute(line, '^\s*buffer\>', 'vert sbuffer', '')
		return "\<C-U>" .. new .. "\<CR>"
	endif
	return "\<C-v>"
enddef

# Initialise files cache.
var filescache: list<string> = []

# Get a list of all files using built-in globpath.
def GlobFiles(): list<string>
	return globpath('.', '**', false, true)
		->filter((_, val) => !isdirectory(val))
		->map((_, val) => fnamemodify(val, ':.'))
enddef

# Get a list of all files using `fd` executable.
def FdFiles(): list<string>
	var find_command = 'fd --exclude .git --follow --full-path --hidden --type file'
	var result = systemlist(find_command)
	if v:shell_error
		echoerr join(result, "\n")
		return []
	endif
	return result
enddef

# Use GlobFiles as the default files fetcher.
var FilesFetcher = GlobFiles

# Use fd to find files if it's available.
if executable('fd')
	FilesFetcher = FdFiles
endif

# Obtain fuzzy-matched list of filenames for the :find command.
def FindFunc(file: string, _: bool): list<string>
	if empty(filescache)
		filescache = FilesFetcher()
	endif
	return file == '' ? filescache : matchfuzzy(filescache, file)
enddef

# Empty the files cache on cmdline entry.
def ClearFilesCache()
	filescache = []
enddef

# Set findfunc but only if it's supported.
if exists('+findfunc')
	&findfunc = expand('<SID>') .. 'FindFunc'
else
	set path+=**
endif

# Re-open last command pre-filled for editing
def ResumeLastCmd()
	feedkeys(':' .. histget(':'), 'tn')
enddef

# Load git hunks into quickfix list
def GitHunksToQF()
	# --relative makes paths resolvable when cwd is not the repository root
	var lines = systemlist('git diff --no-ext-diff -U0 --relative')
	if v:shell_error
		echohl ErrorMsg
		echomsg 'git diff failed'
		echohl None
		return
	endif
	if empty(lines)
		setqflist([], ' ', {title: 'Git Hunks', items: []})
		cclose
		echomsg 'No git hunks found'
		return
	endif
	setqflist([], ' ', {
		title: 'Git Hunks',
		lines: lines,
		efm: '%-Pdiff --git a/%f b/%.%#,'
			.. '@@ -%\d%\+%.%# +%l%.%# @@ %m,'
			.. '@@ -%\d%\+%.%# +%l%.%# @@,'
			.. '%-G%.%#',
	})
	copen
enddef

# Set up Git TUI client
if executable('lazygit')
	def Git()
		silent !lazygit
		redraw!
	enddef
	nnoremap <c-g> <ScriptCmd>Git()<CR>
endif

def FormatFile()
	if &formatprg == ''
		return
	endif
	var formatted = systemlist(&formatprg, bufnr())
	if v:shell_error
		# Warn without throwing so the write still goes through unformatted
		echohl WarningMsg
		echomsg printf(
			'formatprg "%s" exited with status %d, wrote unformatted buffer',
			&formatprg,
			v:shell_error
		)
		echohl None
		return
	endif
	# Leave the buffer untouched when already formatted to keep undo history
	# and marks intact
	if empty(formatted) || formatted == getline(1, '$')
		return
	endif
	var view = winsaveview()
	setline(1, formatted)
	if line('$') > len(formatted)
		deletebufline('%', len(formatted) + 1, '$')
	endif
	winrestview(view)
enddef

augroup autoformat
	autocmd!
	autocmd BufWritePre * FormatFile()
augroup END

augroup cmdline_autocomplete
	autocmd!
	# Trigger cmdline autocompletion
	if exists('*wildtrigger')
		autocmd CmdlineChanged [:\/\?] wildtrigger()
	endif
	# Empty files cache on cmdline entry
	autocmd CmdlineEnter : ClearFilesCache()
augroup END

# Enable built-in packages
silent! packadd comment
silent! packadd hlyank
g:hlyank_duration = 150
silent! packadd nohlsearch
