---
- name: Check Oh My Zsh directory
  register: omz
  ansible.builtin.stat:
    path: ~/.oh-my-zsh
- name: Download Oh My Zsh installer
  when: not omz.stat.isdir
  ansible.builtin.get_url:
    url: https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    dest: /tmp/install-ohmyz.sh
    mode: "755"
- name: Install Oh My Zsh
  when: not omz.stat.isdir
  ansible.builtin.shell:
    cmd: /tmp/install-ohmyz.sh
    creates: ~/.oh-my-zsh
