---
- name: Download Oh My Zsh installer
  ansible.builtin.get_url:
    # yamllint disable-line rule:line-length
    url: https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    dest: /tmp/install-ohmyz.sh
    mode: "755"
- name: Install Oh My Zsh
  ansible.builtin.shell:
    cmd: /tmp/install-ohmyz.sh
    creates: ~/.oh-my-zsh
