#!/usr/bin/env fish

# Oh-My-Zsh jj plugin abbreviations.
# Source: https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/jj/jj.plugin.zsh

abbr -a jja -- 'jj abandon'
abbr -a jjb -- 'jj bookmark'
abbr -a jjba -- 'jj bookmark advance'
abbr -a jjbc -- 'jj bookmark create'
abbr -a jjbd -- 'jj bookmark delete'
abbr -a jjbf -- 'jj bookmark forget'
abbr -a jjbl -- 'jj bookmark list'
abbr -a jjblc -- 'jj bookmark list --conflicted'
abbr -a jjblt -- 'jj bookmark list --tracked'
abbr -a jjbm -- 'jj bookmark move'
abbr -a jjbr -- 'jj bookmark rename'
abbr -a jjbs -- 'jj bookmark set'
abbr -a jjbt -- 'jj bookmark track'
abbr -a jjbu -- 'jj bookmark untrack'
abbr -a jjc -- 'jj commit'
abbr -a jjcmsg -- 'jj commit --message'
abbr -a jjd -- 'jj diff'
abbr -a jjdfs -- 'jj diff --revision "stack()"'
abbr -a jjdmsg -- 'jj desc --message'
abbr -a jjds -- 'jj desc'
abbr -a jje -- 'jj edit'
abbr -a jjf -- 'jj fix'
abbr -a jjgcl -- 'jj git clone'
abbr -a jjgf -- 'jj git fetch'
abbr -a jjgfa -- 'jj git fetch --all-remotes'
abbr -a jjgp -- 'jj git push'
abbr -a jjgpa -- 'jj git push --all'
abbr -a jjgpd -- 'jj git push --deleted'
abbr -a jjgpn -- 'jj git push --change @'
abbr -a jjgpt -- 'jj git push --tracked'
abbr -a jjl -- 'jj log'
abbr -a jjla -- 'jj log --revision "all()"'
abbr -a jjls -- 'jj log --revision "stack()"'
abbr -a jjn -- 'jj new'
abbr -a jjnt -- 'jj new "trunk()"'
abbr -a jjrb -- 'jj rebase'
abbr -a jjrbm -- 'jj rebase --onto "trunk()"'
abbr -a jjrs -- 'jj restore'
abbr -a jjrt -- 'cd (jj root || echo .)'
abbr -a jjsp -- 'jj split'
abbr -a jjsq -- 'jj squash'
abbr -a jjsqp -- 'jj squash && jj git push'
abbr -a jjsqs -- 'jj squash --revision "stack()"'
abbr -a jjst -- 'jj status'
