#!/usr/bin/env fish

# Oh-My-Zsh jj plugin abbreviations.
# Source: https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/jj/jj.plugin.zsh

abbr -a jja --description='abandon revision' -- 'jj abandon'
abbr -a jjb --description='manage bookmarks' -- 'jj bookmark'
abbr -a jjba --description='advance bookmark' -- 'jj bookmark advance'
abbr -a jjbc --description='create bookmark' -- 'jj bookmark create'
abbr -a jjbd --description='delete bookmark' -- 'jj bookmark delete'
abbr -a jjbf --description='forget bookmark' -- 'jj bookmark forget'
abbr -a jjbl --description='list bookmarks' -- 'jj bookmark list'
abbr -a jjblc --description='list conflicted bookmarks' -- 'jj bookmark list --conflicted'
abbr -a jjblt --description='list tracked bookmarks' -- 'jj bookmark list --tracked'
abbr -a jjbm --description='move bookmark' -- 'jj bookmark move'
abbr -a jjbr --description='rename bookmark' -- 'jj bookmark rename'
abbr -a jjbs --description='set bookmark' -- 'jj bookmark set'
abbr -a jjbt --description='track bookmark' -- 'jj bookmark track'
abbr -a jjbu --description='untrack bookmark' -- 'jj bookmark untrack'
abbr -a jjc --description='commit changes' -- 'jj commit'
abbr -a jjcmsg --description='commit with message' -- 'jj commit --message'
abbr -a jjd --description='show diff' -- 'jj diff'
abbr -a jjdfs --description='diff revision stack' -- 'jj diff --revision "stack()"'
abbr -a jjdmsg --description='set description message' -- 'jj desc --message'
abbr -a jjds --description='edit description' -- 'jj desc'
abbr -a jje --description='edit revision' -- 'jj edit'
abbr -a jjf --description='update files with fixes' -- 'jj fix'
abbr -a jjgcl --description='clone Git repository' -- 'jj git clone'
abbr -a jjgf --description='fetch Git remotes' -- 'jj git fetch'
abbr -a jjgfa --description='fetch all Git remotes' -- 'jj git fetch --all-remotes'
abbr -a jjgp --description='push to Git remote' -- 'jj git push'
abbr -a jjgpa --description='push all bookmarks' -- 'jj git push --all'
abbr -a jjgpd --description='push deleted bookmarks' -- 'jj git push --deleted'
abbr -a jjgpn --description='push working copy' -- 'jj git push --change @'
abbr -a jjgpt --description='push all tracked bookmarks' -- 'jj git push --tracked'
abbr -a jjl --description='show revision log' -- 'jj log'
abbr -a jjla --description='show all revisions' -- 'jj log --revision "all()"'
abbr -a jjls --description='show revision stack' -- 'jj log --revision "stack()"'
abbr -a jjn --description='create new revision' -- 'jj new'
abbr -a jjnt --description='create revision on trunk' -- 'jj new "trunk()"'
abbr -a jjrb --description='rebase revision' -- 'jj rebase'
abbr -a jjrbm --description='rebase revision onto trunk' -- 'jj rebase --onto "trunk()"'
abbr -a jjrs --description='restore files' -- 'jj restore'
abbr -a jjrt --description='change to repository root' -- 'cd (jj root || echo .)'
abbr -a jjsp --description='split revision' -- 'jj split'
abbr -a jjsq --description='squash revision' -- 'jj squash'
abbr -a jjsqp --description='squash revision and push' -- 'jj squash && jj git push'
abbr -a jjsqs --description='squash revision stack' -- 'jj squash --revision "stack()"'
abbr -a jjst --description='show repository status' -- 'jj status'
