#!/usr/bin/env fish

# Oh-My-Zsh podman plugin abbreviations.
# Source: https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/podman/podman.plugin.zsh

abbr -a 'prm!' --description='force remove container' -- 'podman container rm --force'
abbr -a pbl --description='build image' -- 'podman build'
abbr -a pcin --description='inspect container' -- 'podman container inspect'
abbr -a pcls --description='list containers' -- 'podman container ls'
abbr -a pclsa --description='list all containers' -- 'podman container ls --all'
abbr -a pib --description='build image' -- 'podman image build'
abbr -a pii --description='inspect image' -- 'podman image inspect'
abbr -a pils --description='list images' -- 'podman image ls'
abbr -a pipu --description='push image' -- 'podman image push'
abbr -a pirm --description='remove image' -- 'podman image rm'
abbr -a pit --description='tag image' -- 'podman image tag'
abbr -a plo --description='show container logs' -- 'podman container logs'
abbr -a pnc --description='create network' -- 'podman network create'
abbr -a pncn --description='connect container to network' -- 'podman network connect'
abbr -a pndcn --description='disconnect container from network' -- 'podman network disconnect'
abbr -a pni --description='inspect network' -- 'podman network inspect'
abbr -a pnls --description='list networks' -- 'podman network ls'
abbr -a pnrm --description='remove network' -- 'podman network rm'
abbr -a ppo --description='show container ports' -- 'podman container port'
abbr -a ppu --description='pull image' -- 'podman pull'
abbr -a pr --description='run container' -- 'podman container run'
abbr -a prit --description='run interactive container' -- 'podman container run --interactive --tty'
abbr -a prm --description='remove container' -- 'podman container rm'
abbr -a prs --description='restart container' -- 'podman container restart'
abbr -a pst --description='start container' -- 'podman container start'
abbr -a psta --description='stop running containers' -- 'podman stop (podman ps --quiet)'
abbr -a pstp --description='stop container' -- 'podman container stop'
abbr -a ptop --description='show container processes' -- 'podman top'
abbr -a pvi --description='inspect volume' -- 'podman volume inspect'
abbr -a pvls --description='list volumes' -- 'podman volume ls'
abbr -a pxc --description='execute command in container' -- 'podman container exec'
abbr -a pxcit --description='execute interactive command in container' -- 'podman container exec --interactive --tty'
