---
- name: Add GitHub CLI repository
  become: true
  ansible.builtin.yum_repository:
    baseurl: https://cli.github.com/packages/rpm/gh-cli.repo
    description: GitHub CLI
    name: gh-cli
    state: present
- name: Fedora packages installed
  become: true
  ansible.builtin.dnf:
    pkg: "{{ rpm_packages }}"
    state: latest
