---
- name: Add GitHub CLI repository
  become: true
  ansible.builtin.yum_repository:
    baseurl: https://cli.github.com/packages/rpm
    description: GitHub CLI
    gpgkey: >-
      https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x23F3D4EA75716059
    name: gh-cli
    state: present
- name: Enable Ghostty copr
  become: true
  community.general.copr:
    name: pgdev/ghostty
    state: enabled
- name: Fedora packages installed
  become: true
  ansible.builtin.dnf:
    pkg: "{{ rpm_packages }}"
    state: latest
