---
- name: Install macOS packages
  include_tasks: install-macos-packages.yml
  when: ansible_distribution == "MacOSX"
- name: Install deb packages
  include_tasks: install-dev-packages
  when: ansible_distribution == "Linux Mint"
- name: Install rpm packages
  include_tasks: install-rpm-packages.yml
  when: ansible_distribution == "Fedora"
- name: Install Starship
  include_tasks: install-starship.yml
  when: ansible_system == "Linux"
- name: Install Oh My Zsh
  command:
    # yamllint disable-line rule:line-length
    cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    creates: ~/.oh-my-zsh
