---
arch_map:
  aarch64: arm64
  x86_64: amd64
local_bin_dir: ~/.local/bin
brew_packages:
  - fd
  - fzf
  - go-task
  - jq
  - lazygit
  - neovim
  - ripgrep
  - starship
  - yq
deb_packages:
  - fd-find
  - fzf
  - gh
  - git
  - jq
  - neovim
  - ripgrep
  - task
  - vim
  - yq
  - zsh
rpm_packages:
  - alacritty
  - fd-find
  - fzf
  - gh
  - git
  - go-task
  - jq
  - neovim
  - ripgrep
  - vim
  - yq
  - zsh
