---
xdg_config_home: ~/.config
directory_mapping:
  - source: "{{ playbook_dir }}/alacritty"
    target: "{{ xdg_config_home }}/alacritty"
  - source: "{{ playbook_dir }}/neovim"
    target: "{{ xdg_config_home }}/nvim"
  - source: "{{ playbook_dir }}/starship"
    target: "{{ xdg_config_home }}/starship"
  - source: "{{ playbook_dir }}/vim"
    target: "{{ xdg_config_home }}/vim"
  - source: "{{ playbook_dir }}/wezterm"
    target: "{{ xdg_config_home }}/wezterm"
  - source: "{{ playbook_dir }}/task"
    target: "~"
  - source: "{{ playbook_dir }}/zsh"
    target: "~"
