---
name: CI

"on":
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  lint:
    if: ${{ !github.event.pull_request.draft }}
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Actionlint
        # yamllint disable-line rule:line-length
        uses: devops-actions/actionlint@ec02b36684b2f574f1d219ad0a43b082e46bf3e4  # v0.1.13

      - name: Lint YAML Files
        # yamllint disable-line rule:line-length
        uses: karancode/yamllint-github-action@4052d365f09b8d34eb552c363d1141fd60e2aeb2  # v3.0.0
        with:
          yamllint_strict: true

      - name: Check TOML Style
        uses: docker://tamasfe/taplo:0.10.0
        with:
          args: >-
            format
            --check
            --diff
            -o reorder_inline_tables=true
            -o reorder_keys=true

      - name: Lint TOML Files
        uses: docker://tamasfe/taplo:0.10.0
        with:
          args: lint

      - name: Check Lua Style
        # yamllint disable-line rule:line-length
        uses: JohnnyMorganz/stylua-action@76fd70c03e6340ceaf673366712db9b20560b402  # v5.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: v2.1.0
          args: >-
            --column-width 88
            --quote-style AutoPreferDouble
            --check .

      - name: Lint Ansible files
        # yamllint disable-line rule:line-length
        uses: ansible/ansible-lint@e7f397ad6dfa20d274afa17cd7bbedd84ed136f5  # v26.9.0
