---
name: PR
# yamllint disable-line rule:truthy
on:
  - pull_request

jobs:
  automation:
    name: Automation
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Check title
        uses: amannn/action-semantic-pull-request@v5.5.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          scopes: |
            alacritty
            helix
            neovim
            task
            vim
            wezterm
            zsh

      - name: Add labels based on changes
        uses: actions/labeler@v5.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
